#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define PROGRAM_EXIT          "XXX" // sentinel value to exit the loop
#define BADMINTON_PLAYER_FILE "badmintonPlayers.txt" // file name (store in same path as C source code)

#define GENDER_MALE   'M'
#define GENDER_FEMALE 'F'

#define PLAYER_TYPE_SINGLE 'S'
#define PLAYER_TYPE_DOUBLE 'D'
#define PLAYER_TYPE_MIXED  'X'

#define BADMINTON_PLAYER_WRITE_FORMAT "%s|%c|%c|%s|%d\n" // input format, pipe-separated value
#define BADMINTON_PLAYER_READ_FORMAT  "%[^|]|%c|%c|%[^|]|%d\n" // output format, different format specifier was used for
                                                               // reading a string (any characters but a '|')

#pragma warning(disable: 4996)

void storeBadmintonPlayers();
void readBadmintonPlayers();

// Player structure definition
typedef struct Player
{
    char name[50];
    char gender;
    char playerType;
    char countryCode[4];
    int  ranking;
} Player;

int main()
{
    // Q1 (remove comment below to run)
    //storeBadmintonPlayers();

    // Q2 (remove comment below to run)
    //readBadmintonPlayers();

    puts("\n");
    system("pause");
    return 0;
}

void storeBadmintonPlayers()
{
    int  noOfPlayer = 0;
    char exitCode[10];

    do
    {
        Player p;

        printf("Badminton player No. %d", noOfPlayer + 1);
        puts("\n======================\n");


        printf("Name         : ");
        gets(p.name);

        printf("Gender       : ");
        p.gender = getchar();

        rewind(stdin); // clear input buffer to remove the line feed (LF) character generated by the "Enter" key

        printf("Player type  : ");
        p.playerType = getchar();

        rewind(stdin);

        printf("Country code : ");
        gets(p.countryCode);

        printf("Ranking      : ");
        scanf("%d", &p.ranking);

        rewind(stdin);

        FILE *fOutput = fopen(BADMINTON_PLAYER_FILE, "a+"); // create/open the file with append mode

        if (fOutput != NULL) // able to open the file?
        {
            fprintf(fOutput, BADMINTON_PLAYER_WRITE_FORMAT,
                p.name, p.gender, p.playerType, p.countryCode, p.ranking); // write into the file

            fclose(fOutput); // finished writing and close the file properly
        }

        puts("");
        printf("Continue? (XXX to exit) : ");
        gets(exitCode);

        noOfPlayer++;

        system("cls");
    } while (strcmp(exitCode, PROGRAM_EXIT) != 0); // continue loop if not "XXX"

    printf("%d new player(s) added and stored successfully!", noOfPlayer);
}

void readBadmintonPlayers()
{
    int  noOfPlayers = 0;
    FILE *fInput     = fopen(BADMINTON_PLAYER_FILE, "r"); // open the text file for reading

    if (fInput != NULL) // able to open the file?
    {
        Player p;
        

        // Header
        puts("\t\t\t\t LIST OF PLAYERS \n");
        puts("Name \t\t Gender \t Country \t Game Type \t  Ranking");
        puts("-------------------------------------------------------------------------");

        // Continue reading until reach End-of-File (EOF)
        while (fscanf(fInput, BADMINTON_PLAYER_READ_FORMAT, p.name, &p.gender, &p.playerType, p.countryCode, &p.ranking) != EOF)
        {
            char gameType[16];

            if (p.playerType == PLAYER_TYPE_MIXED)
            {
                strcpy(gameType, "Mixed Doubles");
            }
            else
            {
                if (p.gender == GENDER_MALE)
                    strcpy(gameType, "Men's ");
                else if (p.gender == GENDER_FEMALE)
                    strcpy(gameType, "Women's ");

                // shortcut: use conditional operator if only need to cater for 2 possibilities
                strcat(gameType, p.playerType == PLAYER_TYPE_SINGLE ? "Singles" : "Doubles");
            }
            
            noOfPlayers++;
            printf("%s \t %c \t\t %s \t\t %s  \t%d \n", p.name, p.gender, p.countryCode, gameType, p.ranking);
        }

        // Footer
        puts("-------------------------------------------------------------------------");
        printf("\t %d player(s) listed.", noOfPlayers);

        fclose(fInput); // finished reading and close the file properly
    }
}
